version: '3.8'
services:
  app:
    build: .
    container_name: cab_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: mysql:8
    container_name: cab_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cabdb
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:alpine
    container_name: cab_redis
    ports:
      - "6379:6379"
