version: '3.8'
services:
  app:
    build: .
    container_name: cab_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16-alpine
    container_name: cab_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cabbie
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
  redis:
    image: redis:alpine
    container_name: cab_redis
    ports:
      - "6379:6379"
